# Generated by Django 4.2.7 on 2023-11-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_remove_candidatedirectory_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedirectorymodel',
            name='employee_id',
        ),
        migrations.AddConstraint(
            model_name='candidatedirectory',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name'), name='full_name'),
        ),
    ]
